# Generated by Django 4.2.27 on 2026-01-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número da Mesa')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (Pessoas)')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada')], default='LIVRE', max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Prato')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('categoria', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRINCIPAL', 'Prato Principal'), ('BEBIDA', 'Bebida'), ('SOBREMESA', 'Sobremesa')], max_length=20, verbose_name='Categoria')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pratos/', verbose_name='Foto do Prato')),
            ],
        ),
    ]
